%--------------------------------------------------------------------------
%
%
%   GUI FOR RUNNING THE INITIAL CONFIGURATION TOOL 
%--------------------------------------------------------------------------
%
% File Description :
% This is the main file for running the initial configuration tool. The
% tool can be used to setup the initial geometric configuration of the
% bones or reset the geometry to the initial data measured from AMIRA.
%
%--------------------------------------------------------------------------
%
% File Structure :
% The GUI figure is created in IHandle. The pushbuttons are defined next,
% followed by the initialisation script. All the GUI control structures are
% contained in ICGUIHandle. The axis is called InitialVisualisationAxes. 
% All the graphics are contained in a single strucure : IPlotHandles. 
%
%--------------------------------------------------------------------------
%
% Contents of the Interactive GUI structure :
%   PushButton Section
%       ICGUIHandle.Close_Button
%       ICGUIHandle.Save_Visualisation_Button
%       ICGUIHandle.Reset_Button
%
%   Interactive Elements
%       ICGUIHandle.Title
%       ICGUIHandle.Clavicula_Axial_Rotation.Title
%       ICGUIHandle.Clavicula_Axial_Rotation.Slider
%       ICGUIHandle.Clavicula_Axial_Rotation.Edit
%       ICGUIHandle.Clavicula_Elevation_Rotation.Title
%       ICGUIHandle.Clavicula_Elevation_Rotation.Slider
%       ICGUIHandle.Clavicula_Elevation_Rotation.Edit
%       ICGUIHandle.Clavicula_Protraction_Rotation.Title
%       ICGUIHandle.Clavicula_Protraction_Rotation.Slider
%       ICGUIHandle.Clavicula_Protraction_Rotation.Edit
%       ICGUIHandle.Scpula_Tilt_Rotation.Title
%       ICGUIHandle.Scpula_Tilt_Rotation.Slider
%       ICGUIHandle.Scpula_Tilt_Rotation.Edit
%       ICGUIHandle.Scapula_Elevation_Rotation.Title
%       ICGUIHandle.Scapula_Elevation_Rotation.Slider
%       ICGUIHandle.Scapula_Elevation_Rotation.Edit
%       ICGUIHandle.Scapula_Protraction_Rotation.Title
%       ICGUIHandle.Scapula_Protraction_Rotation.Slider
%       ICGUIHandle.Scapula_Protraction_Rotation.Edit
%       ICGUIHandle.Humerus_Axial_Rotation.Title
%       ICGUIHandle.Humerus_Axial_Rotation.Slider
%       ICGUIHandle.Humerus_Axial_Rotation.Edit
%       ICGUIHandle.Humerus_Abduction_Rotation.Title
%       ICGUIHandle.Humerus_Abduction_Rotation.Slider
%       ICGUIHandle.Humerus_Abduction_Rotation.Edit
%       ICGUIHandle.Humerus_Elevation_Rotation.Title
%       ICGUIHandle.Humerus_Elevation_Rotation.Slider
%       ICGUIHandle.Humerus_Elevation_Rotation.Edit
%       ICGUIHandle.Ulna_Flexion_Rotation.Title
%       ICGUIHandle.Ulna_Flexion_Rotation.Slider
%       ICGUIHandle.Ulna_Flexion_Rotation.Edit
%       ICGUIHandle.Radius_Pronation_Rotation.Title
%       ICGUIHandle.Radius_Pronation_Rotation.Slider
%       ICGUIHandle.Radius_Pronation_Rotation.Edit
%--------------------------------------------------------------------------
%
% The graphical hierarchy is :
%   IHandle
%       -> InitialVisualisationAxes
%                       -> IPlotHandles
%
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
% CREATE THE FIGURE
%--------------------------------------------------------------------------
IHandle = figure(...
    'color', 'white',...
    'units', 'normalized',...
    'position', [0.1, 0.1, 0.4, 0.8],...
    'toolbar', 'figure',...
    'name', 'EPFL - LBO UPPER EXTREMITY MODEL: INITIAL CONFIGURATION TOOLBOX');

% Push Button for Closing the GUI
ICGUIHandle.Close_Button = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.95, 0.35, 0.05],...
    'style', 'pushbutton',...
    'string', '<html> <b>- CLOSE GUI -------------------------------------------------</b><br><p style="font-size: 90%;"> <i>Closes this GUI and updates BLDATA</i></p>',...
    'fontsize', 14,...
    'fontweight', 'bold',...
    'callback', INITIAL_CONFIGURATION_script_generator('Close Intial Tool'));

% Push Button for Closing the GUI
ICGUIHandle.Reset_Button = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.9, 0.35, 0.05],...
    'style', 'pushbutton',...
    'string', '<html> <b>- RESET JOINT ANGLES -----------------------------------</b><br><p style="font-size: 90%;"> <i>Resets the Joint angles to original values</i></p>',...
    'fontsize', 14,...
    'fontweight', 'bold',...
    'callback', INITIAL_CONFIGURATION_script_generator('Reset Angles'));

% Push Button for Closing the GUI
ICGUIHandle.Save_Visualisation_Button = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.85, 0.35, 0.05],...
    'style', 'pushbutton',...
    'string', '<html> <b>- SAVE VISUALISATION ------------------------------------</b><br><p style="font-size: 90%;"> <i>Saves the current axis content</i></p>',...
    'fontsize', 14,...
    'fontweight', 'bold',...
    'callback', INITIAL_CONFIGURATION_script_generator('Save Visualisation'));

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% CREATE INTERACTIVE CLAVICULA SLIDER PART
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.8, 0.35, 0.015],...
    'fontsize', 14,...
    'string', 'Set Initial Joint Euler Angles (DEG)',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

%--------------------------------------------------------------------------
% CLAVICULA AXIAL ROTATION
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Clavicula_Axial_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.72, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Clavicula Forward Axial Rotation',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
ICGUIHandle.Clavicula_Axial_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.71, 0.35, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', 0,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
ICGUIHandle.Clavicula_Axial_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.72, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '0',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% CLAVICULA ELEVATION / DEPRESSION
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Clavicula_Elevation_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.66, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Clavicula Elevation (-)/Depression (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angle
ICGUIHandle.Clavicula_Elevation_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.65, 0.35, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', -31.4362,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
ICGUIHandle.Clavicula_Elevation_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.66, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '-31.4362',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% CLAVICULA PROTRACTION / RETRACTION
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Clavicula_Protraction_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.6, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Clavicula Retraction (-) / Protraction (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angle
ICGUIHandle.Clavicula_Protraction_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.59, 0.35, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', -14.8076,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
ICGUIHandle.Clavicula_Protraction_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.6, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '-14.8076',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% CREATE INTERACTIVE SCAPULA SLIDER PART
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% SCAPULA SPINAL TILT ROTATION
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Scapula_Tilt_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.54, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Scapula External Tilt(-)/Internal Tilt (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angle
ICGUIHandle.Scapula_Tilt_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.53, 0.35, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', -8.9392,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
ICGUIHandle.Scapula_Tilt_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.54, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '-8.9392',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% SCAPULA ELEVATION / DEPRESSION
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Scapula_Elevation_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.48, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Scapula Depression (-)/Elevation (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angle
ICGUIHandle.Scapula_Elevation_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.47, 0.35, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', -4.9374,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
ICGUIHandle.Scapula_Elevation_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.48, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '-4.9374',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% SCAPULA PROTRACTION / RETRACTION
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Scapula_Protraction_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.42, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Scapula Retraction (-)/Protraction(+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angle
ICGUIHandle.Scapula_Protraction_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.41, 0.35, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', 29.2987,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
ICGUIHandle.Scapula_Protraction_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.42, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '29.2987',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% CREATE INTERACTIVE HUMERUS SLIDER PART
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% HUMERUS AXIAL ROTATION
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Humerus_Axial_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.36, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Humerus Axial Rotation',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
ICGUIHandle.Humerus_Axial_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.35, 0.35, 0.01],...
    'max', 180,...
    'min', -180,...
    'value', -85.4041,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
ICGUIHandle.Humerus_Axial_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.36, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '-85.4041',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% HUMERUS ABDUCTION / ADDUCTION
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Humerus_Abduction_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.3, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Humerus Adduction (+)/Abduction (-)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
ICGUIHandle.Humerus_Abduction_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.29, 0.35, 0.01],...
    'max', 180,...
    'min', -180,...
    'value', 9.7591,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
ICGUIHandle.Humerus_Abduction_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.3, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '9.7591',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% HUMERUS ELEVATION PLANE
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Humerus_Elevation_Plane.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.24, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Humerus Elevation Plane',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
ICGUIHandle.Humerus_Elevation_Plane.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.23, 0.35, 0.01],...
    'max', 180,...
    'min', -180,...
    'value', 129.6775,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator & Editor
ICGUIHandle.Humerus_Elevation_Plane.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.24, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '129.6775',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% CREATE INTERACTIVE FOREARM SLIDER PART
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% ULNA Extension(-)/Flexion(+)
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Ulna_Flexion_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.18, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Ulna Extension (-)/Flexion (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
ICGUIHandle.Ulna_Flexion_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.17, 0.35, 0.01],...
    'max', 150,...
    'min', 0,...
    'value', 0,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
ICGUIHandle.Ulna_Flexion_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.18, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '0',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% RADIUS Supination (-)/Pronation (+)
%--------------------------------------------------------------------------
% Title
ICGUIHandle.Radius_Pronation_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.12, 0.25, 0.02],...
    'fontsize', 12,...
    'string', 'Radius Supination (-)/Pronation (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
ICGUIHandle.Radius_Pronation_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.65, 0.11, 0.35, 0.01],...
    'max', 0,...
    'min', -155,...
    'value', 0,...
    'style', 'slider',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
ICGUIHandle.Radius_Pronation_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.12, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '0',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', INITIAL_CONFIGURATION_script_generator('Update Joint Angles', 'Value Modified'));

% Create a Help Menu
ICGUIHandle.HelpMenu(1,1) = uimenu(IHandle,...
    'label', 'GUI HELP');
ICGUIHandle.HelpMenu(2,1) = uimenu(ICGUIHandle.HelpMenu(1,1),...
    'label', 'About?',...
    'callback', INITIAL_CONFIGURATION_script_generator('Help'));

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% INITIALISATION SCRIPT
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% Create the Axes
InitialVisualisationAxes = axes(...
    'units', 'normalized',...
    'position', [0.05, 0.05, 0.6, 0.9]);

% Set the Axis
set(IHandle, 'currentaxes', InitialVisualisationAxes); hold on;

% Create the 3-D Meshing Visualisations
IPlotHandles.MeshHandle(1) = VISUALISATION_view_bone_meshing([], MEDATA, 0, BLDATA);
IPlotHandles.MeshHandle(2) = VISUALISATION_view_bone_meshing([], MEDATA, 1, BLDATA);
IPlotHandles.MeshHandle(3) = VISUALISATION_view_bone_meshing([], MEDATA, 2, BLDATA);
IPlotHandles.MeshHandle(4) = VISUALISATION_view_bone_meshing([], MEDATA, 3, BLDATA);
IPlotHandles.MeshHandle(5) = VISUALISATION_view_bone_meshing([], MEDATA, 4, BLDATA);
IPlotHandles.MeshHandle(6) = VISUALISATION_view_bone_meshing([], MEDATA, 5, BLDATA);
IPlotHandles.MeshHandle(7) = VISUALISATION_view_bone_meshing([], MEDATA, 6, BLDATA);


% Create the 3-D Wire Frame Visualisations
IPlotHandles.WireFrameHandle(1) = VISUALISATION_view_bone_wireframe([], 0, BLDATA);
IPlotHandles.WireFrameHandle(2) = VISUALISATION_view_bone_wireframe([], 1, BLDATA);
IPlotHandles.WireFrameHandle(3) = VISUALISATION_view_bone_wireframe([], 2, BLDATA);
IPlotHandles.WireFrameHandle(4) = VISUALISATION_view_bone_wireframe([], 3, BLDATA);
IPlotHandles.WireFrameHandle(5) = VISUALISATION_view_bone_wireframe([], 4, BLDATA);
IPlotHandles.WireFrameHandle(6) = VISUALISATION_view_bone_wireframe([], 5, BLDATA);

%--------------------------------------------------------------------------
% SET THE APPEARANCE OF THE VISUALISATION
%--------------------------------------------------------------------------
% Set some lights to help visualise the model
% light('Position',[ 1,   0,   0],'Style','infinite');
% light('Position',[ 0,   0, -10],'Style','local');
% light('Position',[10, -50,   0],'Style','infinite');
% colormap copper; % Give the bone meshings a bone color.
% %box on;          % Turn the axes box on. It makes is easier to keep track of the orientation.
% material dull;   % Define the bone meshing material. It removes the shiny effect.
% axis equal;      % Correct the apsect ratio.
% zoom(1);       % Zoom in on the visualisation. otherwise it looks very small.    
% view([135, 25]); % Setup the initial camera postion [0,0] is behind horizontally.

light('Position',[1 0 0],'Style','infinite');
light('Position',[0 0 -10],'Style','local');
light('Position',[10 -50 0],'Style','infinite');
colormap copper;
box on;
material dull;
%axis equal;
axis ([-100 800 -200 800 -700 600])
%zoom(1.3);
view([165, 15]);