%--------------------------------------------------------------------------
%
%
%--------------------------------------------------------------------------
%
% File description :
% This file is a script for updating the estimation tool visualisations.
%
%--------------------------------------------------------------------------

% List of Muscle Naems
MSCNames = {'HU Joint Force',...% Scapulo-thoracic Force TS
            'RU Joint Force',...% Scapulo-thoracic Force AI
            'Subclavicular',...
            'Serratus Anterior Upper',...
            'Serratus Anterior Middle',...
            'Serratus Anterior Lower',...
            'Trapezius C1 - C6',...
            'Trapezius C7',...
            'Trapezius T1',...
            'Trapezius T2 - T7',...
            'Levator Scapulae',...
            'Rhomboid Minor',...
            'Rhomboid Major T1 - T2',...
            'Rhomboid Major T3 - T4',...
            'Pectorlis Minor',...
            'Pectoralis Major Clavicular',...
            'Pectoralis Major Sternal',...
            'Pectoralis Minor Ribs',...
            'Latissimus Dorsi Thoracic',...
            'Latissimus Dorsi Lumbar',...
            'Latissimus Dorsi Iliac',...
            'Deltoid Clavicular',...
            'Deltoid Acromial',...
            'Deltoid Scapular',...
            'Supraspinatus',...
            'Infraspinatus',...
            'Subscapularis',...
            'Teres Minor',...
            'Teres Major',...
            'Coracobrachialis',...
            'Triceps Brachii Long',...
            'Triceps Brachii Medial',...
            'Triceps Brachii Lateral',...
            'Biceps Brachii Short',...
            'Biceps Brachii Long',...
            'Brachialis',...
            'Brachioradialis',...
            'Supinator',...
            'Pronator Teres',...
            'Flexor Carpi Radialis',...
            'Flexor Carpi Ulnaris',...
            'Extensor Carpi Radialis Long',...
            'Extensor Carpi Radialis Brevis',...
            'Extensor Carpi Ulnaris',...
            'Joint Reaction Force',...
            'Stability'};
        
% List of Line Types
LineTypeList = {'-', '--', ':', '-.'};

if isequal(get(ESGUIHandle.MenuOptions(2,4), 'checked'), 'off')
    t = linspace(0, str2double(get(ESGUIHandle.TimeFrameEdit, 'string')), size(JRDATA,1)-2);
else
    %t = linspace(0, str2double(get(ESGUIHandle.TimeFrameEdit, 'string')), size(JRDATA,1));
    t_org = linspace(0, str2double(get(ESGUIHandle.TimeFrameEdit, 'string')), size(JRDATA,1)+2);
    t = t_org(1, 1:size(JRDATA,1));
end



% define the maximum force amongst all the muscle and constraint forces to
% set the ylimit of all the graphs

for MuscleID = 1:44
    if MuscleID < 3
        maximum_forces(MuscleID) = max(JRDATA(1:end-2,4*(MuscleID+2)));
    else
        maximum_forces(MuscleID) = max(EFDATA{MuscleID, 1}.Forces(1:end-2,1));
    end    
end

ylimit = max(maximum_forces);

%--------------------------------------------------------------------------
% Muscle forces plot
%--------------------------------------------------------------------------
for MuscleId = 1:44
    
    if MuscleId < 3
        % Set the current axes
        set(ESHandle, 'currentaxes', ESVisualisationAxis.Muscle(42+MuscleId));
        
        if isequal(get(ESGUIHandle.MenuOptions(2,4), 'checked'), 'off')
            %plot(t, EFDATA{MuscleId, 1}.Forces(1:end-2,1), 'linewidth', 2, 'color', 'red');
            plot(t', JRDATA(1:end-2,4*(MuscleId+2)), 'linewidth', 2, 'color', 'red'); % 4*(MuscleId+2) ---> to give 12 and 16 
        else
            %plot(t, EFDATA{MuscleId, 1}.Forces(:,1), 'linewidth', 2, 'color', 'red');
            plot(t', JRDATA(:,4*(MuscleId+2)), 'linewidth', 2, 'color', 'red');
            
        end
        
        legend(MSCNames{1,MuscleId});
        set(ESVisualisationAxis.Muscle(42+MuscleId),...
            'xtick', [],...
            'ytick', [],...
            'box', 'on',...
            'xlim', [0 str2double(get(ESGUIHandle.TimeFrameEdit, 'string'))],...
            'ylim', [-1 ylimit],...
            'buttondownfcn', ESTIMATION_TOOL_script_generator('View Data', MuscleId));
    else
        % Set the current axes
        set(ESHandle, 'currentaxes', ESVisualisationAxis.Muscle(MuscleId-2));
        
        if isequal(get(ESGUIHandle.MenuOptions(2,4), 'checked'), 'off')
            plot(t, EFDATA{MuscleId, 1}.Forces(1:end-2,1), 'linewidth', 2, 'color', 'red');
        else
            plot(t, EFDATA{MuscleId, 1}.Forces(:,1), 'linewidth', 2, 'color', 'red');
        end
        
        
        legend(MSCNames{1,MuscleId});
        set(ESVisualisationAxis.Muscle(MuscleId-2),...
            'xtick', [],...
            'ytick', [],...
            'box', 'on',...
            'xlim', [0 str2double(get(ESGUIHandle.TimeFrameEdit, 'string'))],...
            'ylim', [-1 ylimit],...
            'buttondownfcn', ESTIMATION_TOOL_script_generator('View Data', MuscleId));
    end   
end

%--------------------------------------------------------------------------
% Joint Reaction force plot
%--------------------------------------------------------------------------
% Set the Joint reaction force plot
set(ESHandle, 'currentaxes', ESVisualisationAxis.Muscle(45,1));

% Create the X-axis time vector
if isequal(get(ESGUIHandle.MenuOptions(2,4), 'checked'), 'off')
    plot(t', JRDATA(1:end-2,4), 'linewidth', 2, 'color', 'red');
else
    plot(t', JRDATA(:,4), 'linewidth', 2, 'color', 'red');
end

set(ESVisualisationAxis.Muscle(45),...
    'xtick', [],...
    'ytick', [],...
    'xlim', [0 str2double(get(ESGUIHandle.TimeFrameEdit, 'string'))],...
    'box', 'on',...
    'buttondownfcn', ESTIMATION_TOOL_script_generator('View Data', 45));
%--------------------------------------------------------------------------
% GH Joint Stability Criterion Plot
%--------------------------------------------------------------------------
% Create the glenoid stability plot
teta = linspace(0, 2*pi, 100);
Hay = DYDATA.ConeDimensions(1);
Haz = DYDATA.ConeDimensions(2);

Py = Hay*cos(teta);
Pz = Haz*sin(teta);
set(ESHandle, 'currentaxes', ESVisualisationAxis.Muscle(46,1));
hold off;
plot(Py, Pz, 'color', [0.7 0.7 0.7], 'linewidth', 2);
hold on;
if isequal(get(ESGUIHandle.MenuOptions(2,4), 'checked'), 'off')
    plot(JRDATA(1:end-2,6), JRDATA(1:end-2,7), 'linewidth', 2, 'marker', 'o');
else
    plot(JRDATA(:,6), JRDATA(:,7), 'linewidth', 2, 'marker', 'o');
end

set(ESVisualisationAxis.Muscle(46),...
    'xtick', [],...
    'ytick', [],...
    'box', 'on',...
    'buttondownfcn', ESTIMATION_TOOL_script_generator('View Data', 46));

 
%--------------------------------------------------------------------------
% display a message for the user to inform him/her that all the
% optimization steps were conducted succesfully, ofcourse if this is the
% case
%--------------------------------------------------------------------------

Annouce_prob = [];
ProblemId = 1;
for TimeId = 1:length(EFDATA{45, 1})
    if ~(EFDATA{45, 1}(TimeId) == 1)
        Annouce_prob(1, ProblemId) = TimeId;
        ProblemId = 1 + ProblemId;
    end
end

if isempty(Annouce_prob)
    msgbox(['All the load-sharing steps were conducted successfuly'], 'Success');
else
    msgbox(['Problem in the following load-sharing steps were detected, check the optimization display details: ',...
           num2str(Annouce_prob)], 'Failure');
end

% free up the workspace memory
clear MSCNames LineTypeList t_org t MuscleID maximum_forces ylimit MuscleId teta Hay Haz Py Pz

 
