%{
  GUI FOR RUNNING THE MUSCLE TOOL 
--------------------------------------------------------------------------

File Structure :
The GUI figure is created in MHandle. The pushbuttons are defined next,
followed by the initialisation script. All the GUI control structures are
contained in MGUIHandle. The axis is called MuscleVisualisationAxes. 
All the graphics are contained in a single strucure : MPlotHandles. 

--------------------------------------------------------------------------

Contents of the Interactive GUI structure :
  PushButton Section
      MGUIHandle.Close_Button
      MGUIHandle.Save_Visualisation_Button
      MGUIHandle.Update_Visualisation_Button

  Individual Musle Menu Items
      MGUIHandle.Muscle_Wrap_Menu.MainList
      MGUIHandle.Muscle_Wrap_Menu.Options
      MGUIHandle.Muscle_Wrap_Menu.Interpolation
      MGUIHandle.Muscle_Wrap_Menu.SegNumber
      
  All Muscle Menu Items
      MGUIHandle.All_Muscle_Wrap_Menu.MainList
      MGUIHandle.All_Muscle_Wrap_Menu.Options
      MGUIHandle.All_Muscle_Wrap_Menu.Interpolation
      MGUIHandle.All_Muscle_Wrap_Menu.SegNumber

--------------------------------------------------------------------------

The graphical hierarchy is :
  MHandle
      -> MuscleVisualisationAxes
                      -> MPlotHandles

--------------------------------------------------------------------------
%}
%--------------------------------------------------------------------------
% CREATE THE FIGURE
%--------------------------------------------------------------------------
MHandle = figure(...
    'color', 'white',...
    'units', 'normalized',...
    'position', [0.1, 0.1, 0.4, 0.8],...
    'toolbar', 'figure',...
    'name', 'EPFL - LBO Upper Extremity Model: MUSCLE WRAPPING TOOLBOX');

% Push Button for Closing the GUI
MGUIHandle.Close_Button = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.95, 0.3, 0.05],...
    'style', 'pushbutton',...
    'string', 'CLOSE TOOL',...
    'fontsize', 14,...
    'fontweight', 'bold',...
    'callback', MUSCLE_TOOL_script_generator('Close Muscle Tool'));

% Push Button for saving visualization
MGUIHandle.Save_Visualsation_Button = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.9, 0.3, 0.05],...
    'style', 'pushbutton',...
    'string', 'SAVE VISULALISATION',...
    'fontsize', 14,...
    'fontweight', 'bold',...
    'callback', MUSCLE_TOOL_script_generator('Save Visualisation'));

% Push Button for updating the visualization
MGUIHandle.Update_Visualisation_Button = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.85, 0.3, 0.05],...
    'style', 'pushbutton',...
    'string', 'UPDATE VISULALISATION',...
    'fontsize', 14,...
    'fontweight', 'bold',...
    'callback', MUSCLE_TOOL_script_generator('Update Visualisation'));

% Push Button to reset the angles
MGUIHandle.Reset_Button = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.00, 0.3, 0.05],...
    'style', 'pushbutton',...
    'string', 'RESET ANGLES',...
    'fontsize', 14,...
    'fontweight', 'bold',...
    'callback', MUSCLE_TOOL_script_generator('Reset Angles'));

% Push Button to view the origins
MGUIHandle.Origin_Visualisation_Button = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.8, 0.3, 0.02],...
    'style', 'radiobutton',...
    'string', 'View Origins',...
    'value', 1,...
    'fontsize', 14,...
    'backgroundcolor', 'white',...
    'fontweight', 'bold');

% Push Button to view the insertions
MGUIHandle.Insertion_Visualisation_Button = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.75, 0.3, 0.02],...
    'style', 'radiobutton',...
    'string', 'View Insertions',...
    'value', 1,...
    'fontsize', 14,...
    'backgroundcolor', 'white',...
    'fontweight', 'bold');

%--------------------------------------------------------------------------
% CLAVICULA AXIAL ROTATION
%--------------------------------------------------------------------------
% Title
MGUIHandle.Clavicula_Axial_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.68, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Clavicula Forward Axial Rotation',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
MGUIHandle.Clavicula_Axial_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.67, 0.3, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', 0,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
MGUIHandle.Clavicula_Axial_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.68, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '0',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% CLAVICULA ELEVATION / DEPRESSION
%--------------------------------------------------------------------------
% Title
MGUIHandle.Clavicula_Elevation_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.62, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Clavicula Elevation (-)/Depression (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angle
MGUIHandle.Clavicula_Elevation_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.61, 0.3, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', -31.4362,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
MGUIHandle.Clavicula_Elevation_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.62, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '-31.4362',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% CLAVICULA PROTRACTION / RETRACTION
%--------------------------------------------------------------------------
% Title
MGUIHandle.Clavicula_Protraction_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.56, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Clavicula Retraction (-) / Protraction (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angle
MGUIHandle.Clavicula_Protraction_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.55, 0.3, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', -14.8076,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
MGUIHandle.Clavicula_Protraction_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.56, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '-14.8076',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% CREATE INTERACTIVE SCAPULA SLIDER PART
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% SCAPULA SPINAL TILT ROTATION
%--------------------------------------------------------------------------
% Title
MGUIHandle.Scapula_Tilt_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.5, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Scapula External Tilt(-)/Internal Tilt (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angle
MGUIHandle.Scapula_Tilt_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.49, 0.3, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', -8.9392,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
MGUIHandle.Scapula_Tilt_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.5, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '-8.9392',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% SCAPULA ELEVATION / DEPRESSION
%--------------------------------------------------------------------------
% Title
MGUIHandle.Scapula_Elevation_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.44, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Scapula Depression (-)/Elevation (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angle
MGUIHandle.Scapula_Elevation_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.43, 0.3, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', -4.9374,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
MGUIHandle.Scapula_Elevation_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.44, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '-4.9374',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% SCAPULA PROTRACTION / RETRACTION
%--------------------------------------------------------------------------
% Title
MGUIHandle.Scapula_Protraction_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.38, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Scapula Retraction (-)/Protraction(+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angle
MGUIHandle.Scapula_Protraction_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.37, 0.3, 0.01],...
    'max', 90,...
    'min', -90,...
    'value', 29.2987,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
MGUIHandle.Scapula_Protraction_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.38, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '29.2987',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% CREATE INTERACTIVE HUMERUS SLIDER PART
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% HUMERUS AXIAL ROTATION
%--------------------------------------------------------------------------
% Title
MGUIHandle.Humerus_Axial_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.32, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Humerus Axial Rotation',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
MGUIHandle.Humerus_Axial_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.31, 0.3, 0.01],...
    'max', 180,...
    'min', -180,...
    'value', -85.4041,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
MGUIHandle.Humerus_Axial_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.32, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '-85.4041',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% HUMERUS ABDUCTION / ADDUCTION
%--------------------------------------------------------------------------
% Title
MGUIHandle.Humerus_Abduction_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.26, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Humerus Adduction (+)/Abduction (-)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
MGUIHandle.Humerus_Abduction_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.25, 0.3, 0.01],...
    'max', 180,...
    'min', -180,...
    'value', 9.7591,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator
MGUIHandle.Humerus_Abduction_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.26, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '9.7591',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% HUMERUS ELEVATION PLANE
%--------------------------------------------------------------------------
% Title
MGUIHandle.Humerus_Elevation_Plane.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.2, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Humerus Elevation Plane',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
MGUIHandle.Humerus_Elevation_Plane.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.19, 0.3, 0.01],...
    'max', 180,...
    'min', -180,...
    'value', 129.6775,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator & Editor
MGUIHandle.Humerus_Elevation_Plane.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.2, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '129.6775',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% ULNA Extension(-)/Flexion(+)
%--------------------------------------------------------------------------
% Title
MGUIHandle.Ulna_Flexion_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.14, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Ulna Extension (-)/Flexion (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
MGUIHandle.Ulna_Flexion_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.13, 0.3, 0.01],...
    'max', 150,...
    'min', 0,...
    'value', 0,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator & Editor
MGUIHandle.Ulna_Flexion_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.14, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '0',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
% RADIUS Supination (-)/Pronation (+)
%--------------------------------------------------------------------------
% Title
MGUIHandle.Radius_Pronation_Rotation.Title = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.08, 0.2, 0.02],...
    'fontsize', 10,...
    'string', 'Radius Supination (-)/Pronation (+)',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'text');

% Slider for changing the angles
MGUIHandle.Radius_Pronation_Rotation.Slider = uicontrol(...
    'units', 'normalized',...
    'position', [0.7, 0.07, 0.3, 0.01],...
    'max', 0,...
    'min', -155,...
    'value', 0,...
    'style', 'slider',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Slider Modified'));

% Value Indicator & Editor
MGUIHandle.Radius_Pronation_Rotation.Edit = uicontrol(...
    'units', 'normalized',...
    'position', [0.9, 0.08, 0.1, 0.04],...
    'fontsize', 12,...
    'string', '0',...
    'HorizontalAlignment', 'Left',...
    'backgroundcolor', 'white',...
    'fontweight', 'bold',...
    'style', 'edit',...
    'callback', MUSCLE_TOOL_script_generator('Update Joint Angles', 'Value Modified'));

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% CREATE MUSCLE INTERACTIVE CONSTRUCTION
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% List of Muscle Names
MSCNames = {'Subclavicular',...
            'Serratus Anterior Upper',...
            'Serratus Anterior Middle',...
            'Serratus Anterior Lower',...
            'Trapezius C1 - C6',...
            'Trapezius C7',...
            'Trapezius T1',...
            'Trapezius T2 - T7',...
            'Levator Scapulae',...
            'Rhomboid Minor',...
            'Rhomboid Major T1 - T2',...
            'Rhomboid Major T3 - T4',...
            'Pectorlis Minor',...
            'Pectoralis Major Clavicular',...
            'Pectoralis Major Sternal',...
            'Pectoralis Minor Ribs',...
            'Latissimus Dorsi Thoracic',...
            'Latissimus Dorsi Lumbar',...
            'Latissimus Dorsi Iliac',...
            'Deltoid Clavicular',...
            'Deltoid Acromial',...
            'Deltoid Scapular',...
            'Supraspinatus',...
            'Infraspinatus',...
            'Subscapularis',...
            'Teres Minor',...
            'Teres Major',...
            'Coracobrachialis',...
            'Triceps Brachii Long',...
            'Triceps Brachii Medial',...
            'Triceps Brachii Lateral',...
            'Biceps Brachii Short',...
            'Biceps Brachii Long',...
            'Brachialis',...
            'Brachioradialis',...
            'Supinator',...
            'Pronator Teres',...
            'Flexor Carpi Radialis',...
            'Flexor Carpi Ulnaris',...
            'Extensor Carpi Radialis Long',...
            'Extensor Carpi Radialis Brevis',...
            'Extensor Carpi Ulnaris'};

% MAIN MUSCLE LIST
MGUIHandle.Muscle_Wrap_Menu.MainList = uimenu(...
    MHandle,...
    'label', 'Muscle Properties');

% Interactive part of menu
MGUIHandle.Muscle_Wrap_Menu.Options           = zeros(42,6);   % UI menu for muscle names
MGUIHandle.Muscle_Wrap_Menu.Interpolation     = zeros(42,3);   % UI menu for interpolation choice
MGUIHandle.Muscle_Wrap_Menu.SegNumber         = zeros(42,20);  % UI menu for number of segments

for i = 1:42
    
    MGUIHandle.Muscle_Wrap_Menu.Options(i,1) = uimenu(MGUIHandle.Muscle_Wrap_Menu.MainList,...
        'label', MSCNames{1,i},...
        'UserData', i);
    
    % Visibility Option
    MGUIHandle.Muscle_Wrap_Menu.Options(i,2) = uimenu(MGUIHandle.Muscle_Wrap_Menu.Options(i,1),...
        'label', 'Visible?',...
        'UserData', i,...
        'Checked', 'on',...
        'Callback', MUSCLE_TOOL_script_generator('Menu Functions I', i));
    
    % Object Visibility Option
    MGUIHandle.Muscle_Wrap_Menu.Options(i,3) = uimenu(MGUIHandle.Muscle_Wrap_Menu.Options(i,1),...
        'label', 'Object Visible?',...
        'UserData', i,...
        'Callback', MUSCLE_TOOL_script_generator('Menu Functions II', i));
    
    % Interpolation Type Option
    MGUIHandle.Muscle_Wrap_Menu.Options(i,4) = uimenu(MGUIHandle.Muscle_Wrap_Menu.Options(i,1),...
        'label', 'Interpolation Type',...
        'UserData', i);
    
    % Number of Muscle Segments Option
    MGUIHandle.Muscle_Wrap_Menu.Options(i,5) = uimenu(MGUIHandle.Muscle_Wrap_Menu.Options(i,1),...
        'label', 'Number of Segments',...
        'UserData', i);
    
    % Radius Adjustment Factor Option
    MGUIHandle.Muscle_Wrap_Menu.Options(i,6) = uimenu(MGUIHandle.Muscle_Wrap_Menu.Options(i,1),...
        'label', 'Radius Adjustment Factor',...
        'UserData', 1,...
        'Callback', MUSCLE_TOOL_script_generator('Menu Functions V', i));
    
    % Fill The number of segements for each muscle
    for j = 1:20
        if j == 1
            MGUIHandle.Muscle_Wrap_Menu.SegNumber(i,j) = uimenu(MGUIHandle.Muscle_Wrap_Menu.Options(i,5),...
            'label', num2str(j),...
            'UserData', i, ...
            'callback', MUSCLE_TOOL_script_generator('Menu Functions IV', i, j),...
            'Checked', 'on');
        else
            MGUIHandle.Muscle_Wrap_Menu.SegNumber(i,j) = uimenu(MGUIHandle.Muscle_Wrap_Menu.Options(i,5),...
            'label', num2str(j),...
            'UserData', i, ...
            'callback', MUSCLE_TOOL_script_generator('Menu Functions IV', i, j),...
            'Checked', 'Off');
        end
    end
    
    % List of Possible Interpolation Types
    MGUIHandle.Muscle_Wrap_Menu.Interpolation(i,1) = uimenu(MGUIHandle.Muscle_Wrap_Menu.Options(i,4),...
        'label', 'Linear',...
        'UserData', i,...
        'callback', MUSCLE_TOOL_script_generator('Menu Functions III', i, 1));
    
    MGUIHandle.Muscle_Wrap_Menu.Interpolation(i,2) = uimenu(MGUIHandle.Muscle_Wrap_Menu.Options(i,4),...
        'label', 'Linear 2-line',...
        'UserData', i,...
        'callback', MUSCLE_TOOL_script_generator('Menu Functions III', i, 2),...
        'Checked', 'On');
    
    MGUIHandle.Muscle_Wrap_Menu.Interpolation(i,3) = uimenu(MGUIHandle.Muscle_Wrap_Menu.Options(i,4),...
        'label', '3rd Order Spline',...
        'UserData', i,...
        'callback', MUSCLE_TOOL_script_generator('Menu Functions III', i, 3));
    
end

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% CREATE MENU FOR ALL MUSCLES
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
MGUIHandle.All_Muscle_Wrap_Menu.MainList = uimenu(...
    MHandle,...
    'label', 'Set All Properties');

% Interactive part of menu
MGUIHandle.All_Muscle_Wrap_Menu.Options           = zeros(1,3);   % UI menu for muscle names
MGUIHandle.All_Muscle_Wrap_Menu.Interpolation     = zeros(1,3);   % UI menu for interpolation choice
MGUIHandle.All_Muscle_Wrap_Menu.SegNumber         = zeros(1,20);  % UI menu for number of segments

% All Muscles Visibility Option
MGUIHandle.All_Muscle_Wrap_Menu.Options(1,1) = uimenu(MGUIHandle.All_Muscle_Wrap_Menu.MainList,...
    'label', 'Visible?',...
    'UserData', i,...
    'Checked', 'on',...
    'Callback', MUSCLE_TOOL_script_generator('Menu Functions VI', 1));

% All Muscles Visibility Option
MGUIHandle.All_Muscle_Wrap_Menu.Options(1,2) = uimenu(MGUIHandle.All_Muscle_Wrap_Menu.MainList,...
    'label', 'Interpolation Type',...
    'UserData', i);

% All Muscles Number of Segments
MGUIHandle.All_Muscle_Wrap_Menu.Options(1,3) = uimenu(MGUIHandle.All_Muscle_Wrap_Menu.MainList,...
    'label', 'Number of Segments',...
    'UserData', i);

% Fill The number of segements for each muscle
for j = 1:20
    if j == 1
        MGUIHandle.All_Muscle_Wrap_Menu.SegNumber(1,j) = uimenu(MGUIHandle.All_Muscle_Wrap_Menu.Options(1,3),...
            'label', num2str(j),...
            'UserData', i, ...
            'callback', MUSCLE_TOOL_script_generator('Menu Functions VIII', 1, j),...
            'Checked', 'On');
    else
        MGUIHandle.All_Muscle_Wrap_Menu.SegNumber(1,j) = uimenu(MGUIHandle.All_Muscle_Wrap_Menu.Options(1,3),...
            'label', num2str(j),...
            'UserData', i, ...
            'callback', MUSCLE_TOOL_script_generator('Menu Functions VIII', 1, j),...
            'Checked', 'Off');
    end
end

% List of Possible Interpolation Types
MGUIHandle.All_Muscle_Wrap_Menu.Interpolation(1,1) = uimenu(MGUIHandle.All_Muscle_Wrap_Menu.Options(1,2),...
    'label', 'Linear',...
    'UserData', i,...
    'callback', MUSCLE_TOOL_script_generator('Menu Functions VII', 1, 1));

MGUIHandle.All_Muscle_Wrap_Menu.Interpolation(1,2) = uimenu(MGUIHandle.All_Muscle_Wrap_Menu.Options(1,2),...
    'label', 'Linear 2-line',...
    'UserData', i,...
    'callback', MUSCLE_TOOL_script_generator('Menu Functions VII', 1, 2),...
        'Checked', 'On');

MGUIHandle.All_Muscle_Wrap_Menu.Interpolation(1,3) = uimenu(MGUIHandle.All_Muscle_Wrap_Menu.Options(1,2),...
    'label', '3rd Order Spline',...
    'UserData', i,...
    'callback', MUSCLE_TOOL_script_generator('Menu Functions VII', 1, 3));

% Create a Help UI Menu
MGUIHandle.Help(1,1) = uimenu(MHandle,...
    'label', 'MAIN GUI HELP');
% Create a Help UI Menu
MGUIHandle.Help(2,1) = uimenu(MGUIHandle.Help(1,1),...
    'label', 'About? (Displayed in Command Window)',...
    'callback', MUSCLE_TOOL_script_generator('Help'));

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% CREATE VISUALISATION AXES
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
MuscleVisualisationAxes = axes(...
    'units', 'normalized',...
    'position', [0.1, 0.05, 0.6, 0.9]);

%--------------------------------------------------------------------------
% CREATE VISUALISATION
%--------------------------------------------------------------------------
% Set the Axis
set(MHandle, 'currentaxes', MuscleVisualisationAxes); hold on;

% Create the 3-D Meshing Visualisations
MPlotHandles.MeshHandle(1) = VISUALISATION_view_bone_meshing([], MEDATA, 0, BLDATA);
MPlotHandles.MeshHandle(2) = VISUALISATION_view_bone_meshing([], MEDATA, 1, BLDATA);
MPlotHandles.MeshHandle(3) = VISUALISATION_view_bone_meshing([], MEDATA, 2, BLDATA);
MPlotHandles.MeshHandle(4) = VISUALISATION_view_bone_meshing([], MEDATA, 3, BLDATA);
MPlotHandles.MeshHandle(5) = VISUALISATION_view_bone_meshing([], MEDATA, 4, BLDATA);
MPlotHandles.MeshHandle(6) = VISUALISATION_view_bone_meshing([], MEDATA, 5, BLDATA);
MPlotHandles.MeshHandle(7) = VISUALISATION_view_bone_meshing([], MEDATA, 6, BLDATA);


% Create the 3-D Wire Frame Visualisations
MPlotHandles.WireFrameHandle(1) = VISUALISATION_view_bone_wireframe([], 0, BLDATA);
MPlotHandles.WireFrameHandle(2) = VISUALISATION_view_bone_wireframe([], 1, BLDATA);
MPlotHandles.WireFrameHandle(3) = VISUALISATION_view_bone_wireframe([], 2, BLDATA);
MPlotHandles.WireFrameHandle(4) = VISUALISATION_view_bone_wireframe([], 3, BLDATA);
MPlotHandles.WireFrameHandle(5) = VISUALISATION_view_bone_wireframe([], 4, BLDATA);
MPlotHandles.WireFrameHandle(6) = VISUALISATION_view_bone_wireframe([], 5, BLDATA);

% Create the 3-D Muscle elements
for MuscleId = 1:42
    
    % Origin & Insertion
    MPlotHandles.MuscleOriginHandle(MuscleId)    = VISUALISATION_view_muscle_origins([], MWDATA, BLDATA, MuscleId);
    MPlotHandles.MuscleInsertionHandle(MuscleId) = VISUALISATION_view_muscle_insertions([], MWDATA, BLDATA, MuscleId);
    
    % Muscle Wrapping Object
    MPlotHandles.MuscleObject(MuscleId,1) = surf(zeros(2,2), zeros(2,2), zeros(2,2), 'facecolor', 'blue', 'facealpha', 0.2, 'edgealpha', 0.2, 'edgecolor', 'blue');
    MPlotHandles.MuscleObject(MuscleId,2) = surf(zeros(2,2), zeros(2,2), zeros(2,2), 'facecolor', 'blue', 'facealpha', 0.2, 'edgealpha', 0.2, 'edgecolor', 'blue');
    % Muscle Segements
    for SegmentId = 1:20
        if SegmentId > MWDATA{MuscleId,1}.MSCInfo.NbSegments
            MPlotHandles.MuscleSegments(MuscleId, SegmentId) = plot3(0, 0, 0,...
                'color', 'red', 'linewidth', 2, 'marker', 'o', 'markerfacecolor', 'red', 'markersize', 6);
        else
            MPlotHandles.MuscleSegments(MuscleId, SegmentId) = VISUALISATION_view_muscle_segement([], MWDATA, BLDATA, MuscleId, SegmentId);
        end
    end
end

%--------------------------------------------------------------------------
% SET THE APPEARANCE OF THE VISUALISATION
%--------------------------------------------------------------------------
% Set some lights to help visualise the model
light('Position',[ 1,   0,   0],'Style','infinite');
light('Position',[ 0,   0, -10],'Style','local');
light('Position',[10, -50,   0],'Style','infinite');
colormap copper; % Give the bone meshings a bone color.
%box on;          % Turn the axes box on. It makes is easier to keep track of the orientation.
material dull;   % Define the bone meshing material. It removes the shiny effect.
axis equal;      % Correct the apsect ratio.
zoom(1);       % Zoom in on the visualisation. otherwise it looks very small.    
view([165, 15]); % Setup the initial camera postion [0,0] is behind horizontally.


